### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by auliausu** [ayastreb/money-tracker#21]
Hi Sir @ayastreb , I am a graphics designer and I want to contribute by proposing an logo design . If you will permit me I will start doing it.

thanks and best regards!

**Comment by ayastreb** [comment]
hi! Sure, if you have some ideas - go for it 👍

**Comment by auliausu** [comment]
ok sir, i will come back with some design options

**Comment by auliausu** [comment]
Hello, Sir @ayastreb 

These are my logo proposal for your application. If there any revision, please just tell it.

Version 1.
![version 1-02](https://user-images.githubusercontent.com/9031884/40574071-29ab80aa-60f6-11e8-9511-7f13e86f2115.png)


Version 2.
![version 2-03](https://user-images.githubusercontent.com/9031884/40574074-3376966a-60f6-11e8-84bf-f1201a473f0c.png)

**Comment by auliausu** [comment]
Hello, Sir @ayastreb

These are my logo proposal for your application. If there any revision, please just tell it.

Version 1.
![version 1-02](https://user-images.githubusercontent.com/9031884/40574086-92e1d164-60f6-11e8-974d-6d2aa8c3bd0c.png)

version 2.
![2-03](https://user-images.githubusercontent.com/9031884/40574090-9d7c46d6-60f6-11e8-9337-156721dbd27c.jpg)

**Comment by auliausu** [comment]
Hello, Sir @ayastreb 
is there any feedback from this logo inspiration ?

**Comment by ayastreb** [comment]
Hi, sorry, I'm traveling right now, don't have time

**Comment by auliausu** [comment]
wow, okey sir , never mind, just leave some feedback when you free :) 👍 have a nice travelling

**Comment by ayastreb** [comment]
Hi! Thank you for your proposal! But I'm not sure where to use it, and I
like our current logo more, sorry.

**Comment by auliausu** [comment]
never mind @ayastreb , that's fine 👍
