### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by simon511000** [ayastreb/money-tracker#23]
Hello, how to install money-tracker on a mutual host (OVH) without SSH?

**Comment by lefuturiste** [comment]
ça va être compliqué...

**Comment by simon511000** [comment]
merci. Sinon, je peux l'installer sur mon pc pour l'uploader avec le FTP ?

**Comment by lefuturiste** [comment]
euh oui tu peux le compiler sur ton pc et après l'upload oui

**Comment by lefuturiste** [comment]
alors pour installer

- tu clone ce repo en local
- vérifie que tu as `react-scripts` installé sur ton pc sinon : `npm i -g react-scripts`
- après rend toi dans ton repo local et execute `npm run build`
- là ça prend un peu de temps
- ça a généré un dossier build c'est le contenu de ce dossier qui faut upload voilà :)

**Comment by adonisd** [comment]
Hello,

Just wanted to say, awesome app. 

Can you please tell us how to host the couch DB  server ourselves? I do not see any environment variable for those strings. Is there a way I can set it statically instead of having it go through the sign in process ?

**Comment by ayastreb** [comment]
Hi @adonisd ,

you can use this guide to setup your own CouchDB server - https://github.com/afiskon/install-couchdb/blob/master/install-couchdb.sh - I use DigitalOcean.

To use your own server in the app is a bit trickier :) Right now there is no UI for this, but you can change `userInfo.couchDB` object in localStorage. But it's a hack.

There should be a UI in the app, in Settings -> User section to allow users to update their sync server.
I might implement it later, but if somebody want to pick it up and contribute - I'd be happy to accept a PR 👍
