### ISSUE TITLE
sign in fails

### ISSUE THREAD

**Issue by MartinoMensio** [ayastreb/money-tracker#65]
Hi,
When I try to login to my existing account, I receive no emails with the code. The interface does not display any warning/errors https://app.moneytracker.cc/auth

I also checked in my spam folders but I cannot find the code.

Thanks,
Martino

**Comment by MartinoMensio** [comment]
Today it worked again.

**Comment by ayastreb** [comment]
Hi! Sorry for taking so long to get back to this issue - it should be fixed now by #113
